### PR TITLE
First commit of working C++ and java libraries

### PR DESCRIPTION
**Pull request by jpatton-USGS**
- Creates Java and C++ projects, build.xml and CMakeLists.text files.
- Working first pass implementation of Java and C++ clients
- Includes initial licenses and required libraries
- Includes doc directory containing design documents.

This code is run-tested but has no unit tests, I'm not really sure what there is to test, or how to test it, given the clients are mostly just abstracting the kafka clients for ease of use and configuration.

### CODE REVIEW

**Comment by jmfee-usgs** [comment]
I've only tried the java examples so far, but running into problems.
- hazdev-broker.jar does not include any of the dependent jars, either a) include dependencies, b) build separate jar that includes dependencies, or c) document that users must manually add all jars to classpath.
- add instructions for running examples


Steps to reproduce:

- build jars
```
cd java
ant all
```
- start docker container using steps in readme:
```
docker run -d --name docker-kafka -p 2181:2181 -p 9092:9092 -e KAFKA_ADVERTISED_HOST_NAME=`hostname` usgs/docker-kafka
```
- in separate terminal tail docker logs:
```
docker logs -f docker-kafka
```
- start producer and send a message
```
java -jar dist/examples/ExampleProducer.jar dist/examples/producer.config
test
```
I see the following exception in docker logs
```
[2016-10-19 16:21:38,315] INFO Got user-level KeeperException when processing sessionid:0x157ddbf39300000 type:setData cxid:0x40 zxid:0x18 txntype:-1 reqpath:n/a Error Path:/config/topics/test Error:KeeperErrorCode = NoNode for /config/topics/test (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-19 16:21:38,331] INFO Got user-level KeeperException when processing sessionid:0x157ddbf39300000 type:create cxid:0x41 zxid:0x19 txntype:-1 reqpath:n/a Error Path:/config/topics Error:KeeperErrorCode = NodeExists for /config/topics (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-19 16:21:38,359] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2016-10-19 16:21:38,378] INFO [KafkaApi-0] Auto creation of topic test with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
[2016-10-19 16:21:38,439] INFO Got user-level KeeperException when processing sessionid:0x157ddbf39300000 type:create cxid:0x49 zxid:0x1c txntype:-1 reqpath:n/a Error Path:/brokers/topics/test/partitions/0 Error:KeeperErrorCode = NoNode for /brokers/topics/test/partitions/0 (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-19 16:21:38,451] INFO Got user-level KeeperException when processing sessionid:0x157ddbf39300000 type:create cxid:0x4a zxid:0x1d txntype:-1 reqpath:n/a Error Path:/brokers/topics/test/partitions Error:KeeperErrorCode = NoNode for /brokers/topics/test/partitions (org.apache.zookeeper.server.PrepRequestProcessor)
```

- start consumer
```
java -jar dist/examples/ExampleConsumer.jar dist/examples/consumer.config
```

I see the following exception in the logs
```
[2016-10-19 16:22:43,081] ERROR [KafkaApi-0] Error when handling request {group_id=default.consumer} (kafka.server.KafkaApis)
kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:117)
	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:403)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createTopic(KafkaApis.scala:629)
	at kafka.server.KafkaApis.kafka$server$KafkaApis$$createGroupMetadataTopic(KafkaApis.scala:651)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at kafka.server.KafkaApis$$anonfun$getOrCreateGroupMetadataTopic$1.apply(KafkaApis.scala:657)
	at scala.Option.getOrElse(Option.scala:121)
	at kafka.server.KafkaApis.getOrCreateGroupMetadataTopic(KafkaApis.scala:657)
	at kafka.server.KafkaApis.handleGroupCoordinatorRequest(KafkaApis.scala:818)
	at kafka.server.KafkaApis.handle(KafkaApis.scala:86)
	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:60)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jpatton-USGS** [comment]
The docker exceptions:
```
[2016-10-19 16:21:38,315] INFO Got user-level KeeperException when processing sessionid:0x157ddbf39300000 type:setData cxid:0x40 zxid:0x18 txntype:-1 reqpath:n/a Error Path:/config/topics/test Error:KeeperErrorCode = NoNode for /config/topics/test (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-19 16:21:38,331] INFO Got user-level KeeperException when processing sessionid:0x157ddbf39300000 type:create cxid:0x41 zxid:0x19 txntype:-1 reqpath:n/a Error Path:/config/topics Error:KeeperErrorCode = NodeExists for /config/topics (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-19 16:21:38,359] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2016-10-19 16:21:38,378] INFO [KafkaApi-0] Auto creation of topic test with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
[2016-10-19 16:21:38,439] INFO Got user-level KeeperException when processing sessionid:0x157ddbf39300000 type:create cxid:0x49 zxid:0x1c txntype:-1 reqpath:n/a Error Path:/brokers/topics/test/partitions/0 Error:KeeperErrorCode = NoNode for /brokers/topics/test/partitions/0 (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-19 16:21:38,451] INFO Got user-level KeeperException when processing sessionid:0x157ddbf39300000 type:create cxid:0x4a zxid:0x1d txntype:-1 reqpath:n/a Error Path:/brokers/topics/test/partitions Error:KeeperErrorCode = NoNode for /brokers/topics/test/partitions (org.apache.zookeeper.server.PrepRequestProcessor)
```
Are normal informational zookeeper messages produced when kafka automatically creates a new topic (indicating that an existing topic / partition was not found).

**Comment by jpatton-USGS** [comment]
I cannot reproduce generating the kafka.admin.AdminOperationException using the docker container on my laptop when starting the example consumer.  

The exception indicates that a topic was created or existed that had a replication factor (3) higher than the number of brokers (which for the example use case is 1).  Given that I can see in the logs that the automatically created topic "test" was created with the correct replication factor (1) by the example producer, and the example consumer only subscribes to the topic (and cannot create or modify it), I believe that the exception is unrelated to the example code.

**Comment by jmfee-usgs** [comment]
I'm following the steps in the examples, and still receiving the error.  Can you add more information like explicit commands to be run at each step?


> 1. Build the example jars, by running the command `ant examples` from the /java/
> directory (if the examples have not already been built).

I ran `ant examples from the /java/ directory

> 2. Ensure that the Kafka Docker image is running, or start it,
> [see](../README.md#apache-kafka-docker-image).

I started the kafka container using
```
docker run -d --name docker-kafka -p 2181:2181 -p 9092:9092 usgs/docker-kafka:v0.10.0.1
```

 > 3. In the /java/dist/examples directory, edit the `bootstrap.servers` in
 > consumer.config and producer.config to reflect where the Kafka Docker image is
 > running.

This is running on localhost, so left as is.

 > 4. To run the example consumer, from the /java/dist/examples directory run the
 > command `java -jar ExampleConsumer consumer.config`.

Ran this command


 > 5. To run the example producer, from the /java/dist/examples directory run the
 > command `java -jar ExampleProducer producer.config`.

Ran this command.  The producer *seems* to let me send messages.  The client never receives the messages.  I see a bunch of log statements when the client connects, but no output:
```
[2016-10-25 22:04:20,473] INFO Got user-level KeeperException when processing sessionid:0x157fddf18750000 type:create cxid:0x11c zxid:0xb4 txntype:-1 reqpath:n/a Error Path:/brokers/topics/__consumer_offsets/partitions/1 Error:KeeperErrorCode = NoNode for /brokers/topics/__consumer_offsets/partitions/1 (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-25 22:04:20,511] INFO Got user-level KeeperException when processing sessionid:0x157fddf18750000 type:create cxid:0x11f zxid:0xb7 txntype:-1 reqpath:n/a Error Path:/brokers/topics/__consumer_offsets/partitions/26 Error:KeeperErrorCode = NoNode for /brokers/topics/__consumer_offsets/partitions/26 (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-25 22:04:20,545] INFO Got user-level KeeperException when processing sessionid:0x157fddf18750000 type:create cxid:0x122 zxid:0xba txntype:-1 reqpath:n/a Error Path:/brokers/topics/__consumer_offsets/partitions/30 Error:KeeperErrorCode = NoNode for /brokers/topics/__consumer_offsets/partitions/30 (org.apache.zookeeper.server.PrepRequestProcessor)
[2016-10-25 22:04:20,677] INFO [ReplicaFetcherManager on broker 0] Removed fetcher for partitions [__consumer_offsets,32],[__consumer_offsets,16],[__consumer_offsets,49],[__consumer_offsets,44],[__consumer_offsets,28],[__consumer_offsets,17],[__consumer_offsets,23],[__consumer_offsets,7],[__consumer_offsets,4],[__consumer_offsets,29],[__consumer_offsets,35],[__consumer_offsets,3],[__consumer_offsets,24],[__consumer_offsets,41],[__consumer_offsets,0],[__consumer_offsets,38],[__consumer_offsets,13],[__consumer_offsets,8],[__consumer_offsets,5],[__consumer_offsets,39],[__consumer_offsets,36],[__consumer_offsets,40],[__consumer_offsets,45],[__consumer_offsets,15],[__consumer_offsets,33],[__consumer_offsets,37],[__consumer_offsets,21],[__consumer_offsets,6],[__consumer_offsets,11],[__consumer_offsets,20],[__consumer_offsets,47],[__consumer_offsets,2],[__consumer_offsets,27],[__consumer_offsets,34],[__consumer_offsets,9],[__consumer_offsets,22],[__consumer_offsets,42],[__consumer_offsets,14],[__consumer_offsets,25],[__consumer_offsets,10],[__consumer_offsets,48],[__consumer_offsets,31],[__consumer_offsets,18],[__consumer_offsets,19],[__consumer_offsets,12],[__consumer_offsets,46],[__consumer_offsets,43],[__consumer_offsets,1],[__consumer_offsets,26],[__consumer_offsets,30] (kafka.server.ReplicaFetcherManager)
[2016-10-25 22:04:20,698] INFO Completed load of log __consumer_offsets-0 with log end offset 0 (kafka.log.Log)
[2016-10-25 22:04:20,701] INFO Created log for partition [__consumer_offsets,0] in /tmp/kafka-logs with properties {flush.messages -> 9223372036854775807, message.timestamp.type -> CreateTime, segment.bytes -> 104857600, preallocate -> false, cleanup.policy -> compact, delete.retention.ms -> 86400000, segment.ms -> 604800000, min.insync.replicas -> 1, file.delete.delay.ms -> 60000, retention.ms -> 604800000, max.message.bytes -> 1000012, message.format.version -> 0.10.0-IV1, index.interval.bytes -> 4096, segment.index.bytes -> 10485760, retention.bytes -> -1, segment.jitter.ms -> 0, min.cleanable.dirty.ratio -> 0.5, compression.type -> producer, unclean.leader.election.enable -> true, message.timestamp.difference.max.ms -> 9223372036854775807, flush.ms -> 9223372036854775807}. (kafka.log.LogManager)
[2016-10-25 22:04:20,704] INFO Partition [__consumer_offsets,0] on broker 0: No checkpointed highwatermark is found for partition [__consumer_offsets,0] (kafka.cluster.Partition)
[2016-10-25 22:04:20,726] INFO Completed load of log __consumer_offsets-48 with log end offset 0 (kafka.log.Log)
[2016-10-25 22:04:20,730] INFO Created log for partition [__consumer_offsets,48] in /tmp/kafka-logs with properties {flush.messages -> 9223372036854775807, message.timestamp.type -> CreateTime, segment.bytes -> 104857600, preallocate -> false, cleanup.policy -> compact, delete.retention.ms -> 86400000, segment.ms -> 604800000, min.insync.replicas -> 1, file.delete.delay.ms -> 60000, retention.ms -> 604800000, max.message.bytes -> 1000012, message.format.version -> 0.10.0-IV1, index.interval.bytes -> 4096, segment.index.bytes -> 10485760, retention.bytes -> -1, segment.jitter.ms -> 0, min.cleanable.dirty.ratio -> 0.5, compression.type -> producer, unclean.leader.election.enable -> true, message.timestamp.difference.max.ms -> 9223372036854775807, flush.ms -> 9223372036854775807}. (kafka.log.LogManager)
```

**Comment by jmfee-usgs** [comment]
- cpp build instructions do not seem to work:
```
cd cpp
mkdir build
cd build
cmake ..
make
```
Generates the following error:
```
Scanning dependencies of target hazdev-broker
[ 25%] Building CXX object CMakeFiles/hazdev-broker.dir/src/ClientBase.cpp.o
In file included from /.../hazdev-broker/cpp/src/ClientBase.cpp:1:
/.../hazdev-broker/cpp/include/ClientBase.h:19:10: fatal error: 'rdkafkacpp.h' file not found
#include "rdkafkacpp.h"
         ^
1 error generated.
make[2]: *** [CMakeFiles/hazdev-broker.dir/src/ClientBase.cpp.o] Error 1
make[1]: *** [CMakeFiles/hazdev-broker.dir/all] Error 2
make: *** [all] Error 2
```


Can this be done in a shell script instead of described?  "build.sh" and "build-examples.sh", or similar?

**Comment by jpatton-USGS** [comment]
I missed the extraction step in the instructions, sorry.

**Comment by jpatton-USGS** [comment]
Added issue #5 to add cpp build scripts after this merge.

**Pull request merged**
